---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify
  hosts: instance
  gather_facts: false # Quicker, if you do not need facts
  tasks:
    - name: Assert something
      ansible.builtin.assert:
        that: true
    - name: Assert configuration is valid
      assert:
        that:
          - validation_result.rc == 0
        fail_msg: "Configuration validation failed!"
    - name: Validate the configuration syntax
      command: vector validate /etc/vector/config.toml
      register: validation_result
      failed_when: validation_result.rc != 0
      changed_when: False
